/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
void resetTest(void);
extern void test_Helpers1(void);
extern void test_Normalise(void);
extern void test_SignNoFrac(void);
extern void test_SignWithFrac(void);
extern void test_CmpFracEQ(void);
extern void test_CmpFracGT(void);
extern void test_CmpFracLT(void);
extern void test_AddFullNorm(void);
extern void test_AddFullOflow1(void);
extern void test_AddNsecNorm(void);
extern void test_AddNsecOflow1(void);
extern void test_SubFullNorm(void);
extern void test_SubFullOflow(void);
extern void test_SubNsecNorm(void);
extern void test_SubNsecOflow(void);
extern void test_Neg(void);
extern void test_AbsNoFrac(void);
extern void test_AbsWithFrac(void);
extern void test_Helpers2(void);
extern void test_ToLFPbittest(void);
extern void test_ToLFPrelPos(void);
extern void test_ToLFPrelNeg(void);
extern void test_ToLFPabs(void);
extern void test_FromLFPbittest(void);
extern void test_FromLFPrelPos(void);
extern void test_FromLFPrelNeg(void);
extern void test_LFProundtrip(void);
extern void test_ToString(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "timespecops.c";
  UnityBegin("timespecops.c");
  RUN_TEST(test_Helpers1, 206);
  RUN_TEST(test_Normalise, 226);
  RUN_TEST(test_SignNoFrac, 240);
  RUN_TEST(test_SignWithFrac, 252);
  RUN_TEST(test_CmpFracEQ, 266);
  RUN_TEST(test_CmpFracGT, 279);
  RUN_TEST(test_CmpFracLT, 292);
  RUN_TEST(test_AddFullNorm, 309);
  RUN_TEST(test_AddFullOflow1, 323);
  RUN_TEST(test_AddNsecNorm, 337);
  RUN_TEST(test_AddNsecOflow1, 349);
  RUN_TEST(test_SubFullNorm, 365);
  RUN_TEST(test_SubFullOflow, 379);
  RUN_TEST(test_SubNsecNorm, 393);
  RUN_TEST(test_SubNsecOflow, 405);
  RUN_TEST(test_Neg, 421);
  RUN_TEST(test_AbsNoFrac, 438);
  RUN_TEST(test_AbsWithFrac, 449);
  RUN_TEST(test_Helpers2, 464);
  RUN_TEST(test_ToLFPbittest, 496);
  RUN_TEST(test_ToLFPrelPos, 509);
  RUN_TEST(test_ToLFPrelNeg, 521);
  RUN_TEST(test_ToLFPabs, 533);
  RUN_TEST(test_FromLFPbittest, 548);
  RUN_TEST(test_FromLFPrelPos, 567);
  RUN_TEST(test_FromLFPrelNeg, 580);
  RUN_TEST(test_LFProundtrip, 595);
  RUN_TEST(test_ToString, 614);

  return (UnityEnd());
}
