/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_NonLeapYearFebruary(void);
extern void test_NonLeapYearJune(void);
extern void test_LeapYearFebruary(void);
extern void test_LeapYearDecember(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "ymd2yd.c";
  UnityBegin("ymd2yd.c");
  RUN_TEST(test_NonLeapYearFebruary, 12);
  RUN_TEST(test_NonLeapYearJune, 16);
  RUN_TEST(test_LeapYearFebruary, 21);
  RUN_TEST(test_LeapYearDecember, 25);

  return (UnityEnd());
}
