/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
void resetTest(void);
extern void test_Helpers1(void);
extern void test_Normalise(void);
extern void test_SignNoFrac(void);
extern void test_SignWithFrac(void);
extern void test_CmpFracEQ(void);
extern void test_CmpFracGT(void);
extern void test_CmpFracLT(void);
extern void test_AddFullNorm(void);
extern void test_AddFullOflow1(void);
extern void test_AddUsecNorm(void);
extern void test_AddUsecOflow1(void);
extern void test_SubFullNorm(void);
extern void test_SubFullOflow(void);
extern void test_SubUsecNorm(void);
extern void test_SubUsecOflow(void);
extern void test_Neg(void);
extern void test_AbsNoFrac(void);
extern void test_AbsWithFrac(void);
extern void test_Helpers2(void);
extern void test_ToLFPbittest(void);
extern void test_ToLFPrelPos(void);
extern void test_ToLFPrelNeg(void);
extern void test_ToLFPabs(void);
extern void test_FromLFPbittest(void);
extern void test_FromLFPrelPos(void);
extern void test_FromLFPrelNeg(void);
extern void test_LFProundtrip(void);
extern void test_ToString(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "timevalops.c";
  UnityBegin("timevalops.c");
  RUN_TEST(test_Helpers1, 153);
  RUN_TEST(test_Normalise, 173);
  RUN_TEST(test_SignNoFrac, 187);
  RUN_TEST(test_SignWithFrac, 199);
  RUN_TEST(test_CmpFracEQ, 214);
  RUN_TEST(test_CmpFracGT, 228);
  RUN_TEST(test_CmpFracLT, 242);
  RUN_TEST(test_AddFullNorm, 260);
  RUN_TEST(test_AddFullOflow1, 274);
  RUN_TEST(test_AddUsecNorm, 288);
  RUN_TEST(test_AddUsecOflow1, 300);
  RUN_TEST(test_SubFullNorm, 316);
  RUN_TEST(test_SubFullOflow, 330);
  RUN_TEST(test_SubUsecNorm, 344);
  RUN_TEST(test_SubUsecOflow, 356);
  RUN_TEST(test_Neg, 372);
  RUN_TEST(test_AbsNoFrac, 389);
  RUN_TEST(test_AbsWithFrac, 400);
  RUN_TEST(test_Helpers2, 416);
  RUN_TEST(test_ToLFPbittest, 449);
  RUN_TEST(test_ToLFPrelPos, 464);
  RUN_TEST(test_ToLFPrelNeg, 478);
  RUN_TEST(test_ToLFPabs, 491);
  RUN_TEST(test_FromLFPbittest, 509);
  RUN_TEST(test_FromLFPrelPos, 527);
  RUN_TEST(test_FromLFPrelNeg, 540);
  RUN_TEST(test_LFProundtrip, 554);
  RUN_TEST(test_ToString, 573);

  return (UnityEnd());
}
