/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "config.h"
#include "ntp_stdlib.h"
#include "ntp_fp.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_PositiveInteger(void);
extern void test_NegativeInteger(void);
extern void test_PositiveIntegerWithFraction(void);
extern void test_NegativeIntegerWithFraction(void);
extern void test_RoundingDownToInteger(void);
extern void test_RoundingMiddleToInteger(void);
extern void test_RoundingUpToInteger(void);
extern void test_SingleDecimal(void);
extern void test_MillisecondsRoundingUp(void);
extern void test_MillisecondsRoundingDown(void);
extern void test_UnsignedInteger(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  UnityBegin("lfptostr.c");
  RUN_TEST(test_PositiveInteger, 23);
  RUN_TEST(test_NegativeInteger, 31);
  RUN_TEST(test_PositiveIntegerWithFraction, 39);
  RUN_TEST(test_NegativeIntegerWithFraction, 47);
  RUN_TEST(test_RoundingDownToInteger, 55);
  RUN_TEST(test_RoundingMiddleToInteger, 63);
  RUN_TEST(test_RoundingUpToInteger, 71);
  RUN_TEST(test_SingleDecimal, 79);
  RUN_TEST(test_MillisecondsRoundingUp, 87);
  RUN_TEST(test_MillisecondsRoundingDown, 97);
  RUN_TEST(test_UnsignedInteger, 106);

  return (UnityEnd());
}
