/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_DaySplitMerge();
extern void test_SplitYearDays1();
extern void test_SplitYearDays2();
extern void test_RataDie1();
extern void test_LeapYears1();
extern void test_LeapYears2();
extern void test_RoundTripDate();
extern void test_RoundTripYearStart();
extern void test_RoundTripMonthStart();
extern void test_RoundTripWeekStart();
extern void test_RoundTripDayStart();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "calendar.c";
  UnityBegin("calendar.c");
  RUN_TEST(test_DaySplitMerge, 245);
  RUN_TEST(test_SplitYearDays1, 269);
  RUN_TEST(test_SplitYearDays2, 283);
  RUN_TEST(test_RataDie1, 298);
  RUN_TEST(test_LeapYears1, 308);
  RUN_TEST(test_LeapYears2, 323);
  RUN_TEST(test_RoundTripDate, 341);
  RUN_TEST(test_RoundTripYearStart, 370);
  RUN_TEST(test_RoundTripMonthStart, 386);
  RUN_TEST(test_RoundTripWeekStart, 402);
  RUN_TEST(test_RoundTripDayStart, 418);

  return (UnityEnd());
}
