/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_AddTrustedKeys();
extern void test_AddUntrustedKey();
extern void test_HaveKeyCorrect();
extern void test_HaveKeyIncorrect();
extern void test_AddWithAuthUseKey();
extern void test_EmptyKey();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
	init_auth();

  Unity.TestFile = "authkeys.c";
  UnityBegin("authkeys.c");
  RUN_TEST(test_AddTrustedKeys, 61);
  RUN_TEST(test_AddUntrustedKey, 72);
  RUN_TEST(test_HaveKeyCorrect, 80);
  RUN_TEST(test_HaveKeyIncorrect, 89);
  RUN_TEST(test_AddWithAuthUseKey, 96);
  RUN_TEST(test_EmptyKey, 103);

  return (UnityEnd());
}
