/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_Helpers1();
extern void test_Normalise();
extern void test_SignNoFrac();
extern void test_SignWithFrac();
extern void test_CmpFracEQ();
extern void test_CmpFracGT();
extern void test_CmpFracLT();
extern void test_AddFullNorm();
extern void test_AddFullOflow1();
extern void test_AddUsecNorm();
extern void test_AddUsecOflow1();
extern void test_SubFullNorm();
extern void test_SubFullOflow();
extern void test_SubUsecNorm();
extern void test_SubUsecOflow();
extern void test_Neg();
extern void test_AbsNoFrac();
extern void test_AbsWithFrac();
extern void test_Helpers2();
extern void test_ToLFPbittest();
extern void test_ToLFPrelPos();
extern void test_ToLFPrelNeg();
extern void test_ToLFPabs();
extern void test_FromLFPbittest();
extern void test_FromLFPrelPos();
extern void test_FromLFPrelNeg();
extern void test_LFProundtrip();
extern void test_ToString();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "timevalops.c";
  UnityBegin("timevalops.c");
  RUN_TEST(test_Helpers1, 155);
  RUN_TEST(test_Normalise, 175);
  RUN_TEST(test_SignNoFrac, 189);
  RUN_TEST(test_SignWithFrac, 201);
  RUN_TEST(test_CmpFracEQ, 216);
  RUN_TEST(test_CmpFracGT, 230);
  RUN_TEST(test_CmpFracLT, 244);
  RUN_TEST(test_AddFullNorm, 262);
  RUN_TEST(test_AddFullOflow1, 276);
  RUN_TEST(test_AddUsecNorm, 290);
  RUN_TEST(test_AddUsecOflow1, 302);
  RUN_TEST(test_SubFullNorm, 318);
  RUN_TEST(test_SubFullOflow, 332);
  RUN_TEST(test_SubUsecNorm, 346);
  RUN_TEST(test_SubUsecOflow, 358);
  RUN_TEST(test_Neg, 374);
  RUN_TEST(test_AbsNoFrac, 391);
  RUN_TEST(test_AbsWithFrac, 402);
  RUN_TEST(test_Helpers2, 418);
  RUN_TEST(test_ToLFPbittest, 451);
  RUN_TEST(test_ToLFPrelPos, 466);
  RUN_TEST(test_ToLFPrelNeg, 480);
  RUN_TEST(test_ToLFPabs, 493);
  RUN_TEST(test_FromLFPbittest, 511);
  RUN_TEST(test_FromLFPrelPos, 529);
  RUN_TEST(test_FromLFPrelNeg, 542);
  RUN_TEST(test_LFProundtrip, 556);
  RUN_TEST(test_ToString, 575);

  return (UnityEnd());
}
