/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
void resetTest(void);
extern void test_Encrypt();
extern void test_DecryptValid();
extern void test_DecryptInvalid();
extern void test_IPv4AddressToRefId();
extern void test_IPv6AddressToRefId();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "a_md5encrypt.c";
  UnityBegin("a_md5encrypt.c");
  RUN_TEST(test_Encrypt, 36);
  RUN_TEST(test_DecryptValid, 55);
  RUN_TEST(test_DecryptInvalid, 61);
  RUN_TEST(test_IPv4AddressToRefId, 69);
  RUN_TEST(test_IPv6AddressToRefId, 80);

  return (UnityEnd());
}
