/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
void resetTest(void);
extern void test_Helpers1(void);
extern void test_Normalise(void);
extern void test_SignNoFrac(void);
extern void test_SignWithFrac(void);
extern void test_CmpFracEQ(void);
extern void test_CmpFracGT(void);
extern void test_CmpFracLT(void);
extern void test_AddFullNorm(void);
extern void test_AddFullOflow1(void);
extern void test_AddUsecNorm(void);
extern void test_AddUsecOflow1(void);
extern void test_SubFullNorm(void);
extern void test_SubFullOflow(void);
extern void test_SubUsecNorm(void);
extern void test_SubUsecOflow(void);
extern void test_Neg(void);
extern void test_AbsNoFrac(void);
extern void test_AbsWithFrac(void);
extern void test_Helpers2(void);
extern void test_ToLFPbittest(void);
extern void test_ToLFPrelPos(void);
extern void test_ToLFPrelNeg(void);
extern void test_ToLFPabs(void);
extern void test_FromLFPbittest(void);
extern void test_FromLFPrelPos(void);
extern void test_FromLFPrelNeg(void);
extern void test_LFProundtrip(void);
extern void test_ToString(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "timevalops.c";
  UnityBegin("timevalops.c");
  RUN_TEST(test_Helpers1, 149);
  RUN_TEST(test_Normalise, 169);
  RUN_TEST(test_SignNoFrac, 183);
  RUN_TEST(test_SignWithFrac, 195);
  RUN_TEST(test_CmpFracEQ, 210);
  RUN_TEST(test_CmpFracGT, 224);
  RUN_TEST(test_CmpFracLT, 238);
  RUN_TEST(test_AddFullNorm, 256);
  RUN_TEST(test_AddFullOflow1, 270);
  RUN_TEST(test_AddUsecNorm, 284);
  RUN_TEST(test_AddUsecOflow1, 296);
  RUN_TEST(test_SubFullNorm, 312);
  RUN_TEST(test_SubFullOflow, 326);
  RUN_TEST(test_SubUsecNorm, 340);
  RUN_TEST(test_SubUsecOflow, 352);
  RUN_TEST(test_Neg, 368);
  RUN_TEST(test_AbsNoFrac, 385);
  RUN_TEST(test_AbsWithFrac, 396);
  RUN_TEST(test_Helpers2, 412);
  RUN_TEST(test_ToLFPbittest, 445);
  RUN_TEST(test_ToLFPrelPos, 460);
  RUN_TEST(test_ToLFPrelNeg, 474);
  RUN_TEST(test_ToLFPabs, 487);
  RUN_TEST(test_FromLFPbittest, 505);
  RUN_TEST(test_FromLFPrelPos, 523);
  RUN_TEST(test_FromLFPrelNeg, 536);
  RUN_TEST(test_LFProundtrip, 550);
  RUN_TEST(test_ToString, 569);

  return (UnityEnd());
}
