/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_SingleDigit(void);
extern void test_MultipleDigits(void);
extern void test_Zero(void);
extern void test_MaximumUnsigned32bit(void);
extern void test_Overflow(void);
extern void test_IllegalCharacter(void);
extern void test_IllegalDigit(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "octtoint.c";
  UnityBegin("octtoint.c");
  RUN_TEST(test_SingleDigit, 5);
  RUN_TEST(test_MultipleDigits, 14);
  RUN_TEST(test_Zero, 23);
  RUN_TEST(test_MaximumUnsigned32bit, 32);
  RUN_TEST(test_Overflow, 41);
  RUN_TEST(test_IllegalCharacter, 49);
  RUN_TEST(test_IllegalDigit, 57);

  return (UnityEnd());
}
