/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_SingleDigit(void);
extern void test_MultipleDigits(void);
extern void test_MaxUnsigned(void);
extern void test_Overflow(void);
extern void test_IllegalChar(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "hextoint.c";
  UnityBegin("hextoint.c");
  RUN_TEST(test_SingleDigit, 7);
  RUN_TEST(test_MultipleDigits, 15);
  RUN_TEST(test_MaxUnsigned, 23);
  RUN_TEST(test_Overflow, 31);
  RUN_TEST(test_IllegalChar, 38);

  return (UnityEnd());
}
