/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_RegularPositive(void);
extern void test_RegularNegative(void);
extern void test_PositiveOverflowBoundary(void);
extern void test_NegativeOverflowBoundary(void);
extern void test_PositiveOverflowBig(void);
extern void test_IllegalCharacter(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "atoint.c";
  UnityBegin("atoint.c");
  RUN_TEST(test_RegularPositive, 3);
  RUN_TEST(test_RegularNegative, 11);
  RUN_TEST(test_PositiveOverflowBoundary, 19);
  RUN_TEST(test_NegativeOverflowBoundary, 26);
  RUN_TEST(test_PositiveOverflowBig, 33);
  RUN_TEST(test_IllegalCharacter, 40);

  return (UnityEnd());
}
