/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_Helpers1();
extern void test_Normalise();
extern void test_SignNoFrac();
extern void test_SignWithFrac();
extern void test_CmpFracEQ();
extern void test_CmpFracGT();
extern void test_CmpFracLT();
extern void test_AddFullNorm();
extern void test_AddFullOflow1();
extern void test_AddUsecNorm();
extern void test_AddUsecOflow1();
extern void test_SubFullNorm();
extern void test_SubFullOflow();
extern void test_SubUsecNorm();
extern void test_SubUsecOflow();
extern void test_Neg();
extern void test_AbsNoFrac();
extern void test_AbsWithFrac();
extern void test_LFProundtrip();
extern void test_ToString();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "timevalops.c";
  UnityBegin("timevalops.c");
  RUN_TEST(test_Helpers1, 126);
  RUN_TEST(test_Normalise, 153);
  RUN_TEST(test_SignNoFrac, 167);
  RUN_TEST(test_SignWithFrac, 179);
  RUN_TEST(test_CmpFracEQ, 194);
  RUN_TEST(test_CmpFracGT, 208);
  RUN_TEST(test_CmpFracLT, 222);
  RUN_TEST(test_AddFullNorm, 240);
  RUN_TEST(test_AddFullOflow1, 255);
  RUN_TEST(test_AddUsecNorm, 269);
  RUN_TEST(test_AddUsecOflow1, 281);
  RUN_TEST(test_SubFullNorm, 297);
  RUN_TEST(test_SubFullOflow, 311);
  RUN_TEST(test_SubUsecNorm, 325);
  RUN_TEST(test_SubUsecOflow, 337);
  RUN_TEST(test_Neg, 353);
  RUN_TEST(test_AbsNoFrac, 370);
  RUN_TEST(test_AbsWithFrac, 381);
  RUN_TEST(test_LFProundtrip, 520);
  RUN_TEST(test_ToString, 539);

  return (UnityEnd());
}
