/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "config.h"
#include "ntp_types.h"
#include "ntp_stdlib.h"
#include "fileHandlingTest.h"
#include "kod_management.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_ReadEmptyFile(void);
extern void test_ReadCorrectFile(void);
extern void test_ReadFileWithBlankLines(void);
extern void test_WriteEmptyFile(void);
extern void test_WriteFileWithSingleEntry(void);
extern void test_WriteFileWithMultipleEntries(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  UnityBegin("kodFile.c");
  RUN_TEST(test_ReadEmptyFile, 27);
  RUN_TEST(test_ReadCorrectFile, 35);
  RUN_TEST(test_ReadFileWithBlankLines, 55);
  RUN_TEST(test_WriteEmptyFile, 80);
  RUN_TEST(test_WriteFileWithSingleEntry, 95);
  RUN_TEST(test_WriteFileWithMultipleEntries, 120);

  return (UnityEnd());
}
