/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
void resetTest(void);
extern void test_ValidateGood();
extern void test_ValidateNoHash();
extern void test_ValidateBad();
extern void test_ValidateMalformed();
extern void test_ValidateMalformedShort();
extern void test_ValidateNoLeadZero();
extern void test_tableSelect();
extern void test_loadFileExpire();
extern void test_loadFileTTL();
extern void test_lsQueryPristineState();
extern void test_ls2009faraway();
extern void test_ls2009weekaway();
extern void test_ls2009houraway();
extern void test_ls2009secaway();
extern void test_ls2009onspot();
extern void test_ls2009nodata();
extern void test_ls2009limdata();
extern void test_qryJumpFarAhead();
extern void test_qryJumpAheadToTransition();
extern void test_qryJumpAheadOverTransition();
extern void test_addDynamic();
extern void test_taiEmptyTable();
extern void test_taiTableFixed();
extern void test_taiTableDynamic();
extern void test_taiTableDynamicDeadZone();
extern void test_ls2009seqInsElectric();
extern void test_ls2009seqInsDumb();
extern void test_ls2009seqDelElectric();
extern void test_ls2009seqDelDumb();
extern void test_ls2012seqInsElectric();
extern void test_ls2012seqInsDumb();
extern void test_lsEmptyTableDumb();
extern void test_lsEmptyTableElectric();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "leapsec.c";
  UnityBegin("leapsec.c");
  RUN_TEST(test_ValidateGood, 336);
  RUN_TEST(test_ValidateNoHash, 343);
  RUN_TEST(test_ValidateBad, 350);
  RUN_TEST(test_ValidateMalformed, 357);
  RUN_TEST(test_ValidateMalformedShort, 364);
  RUN_TEST(test_ValidateNoLeadZero, 371);
  RUN_TEST(test_tableSelect, 383);
  RUN_TEST(test_loadFileExpire, 419);
  RUN_TEST(test_loadFileTTL, 436);
  RUN_TEST(test_lsQueryPristineState, 468);
  RUN_TEST(test_ls2009faraway, 480);
  RUN_TEST(test_ls2009weekaway, 497);
  RUN_TEST(test_ls2009houraway, 514);
  RUN_TEST(test_ls2009secaway, 531);
  RUN_TEST(test_ls2009onspot, 548);
  RUN_TEST(test_ls2009nodata, 565);
  RUN_TEST(test_ls2009limdata, 582);
  RUN_TEST(test_qryJumpFarAhead, 603);
  RUN_TEST(test_qryJumpAheadToTransition, 625);
  RUN_TEST(test_qryJumpAheadOverTransition, 647);
  RUN_TEST(test_addDynamic, 673);
  RUN_TEST(test_taiEmptyTable, 851);
  RUN_TEST(test_taiTableFixed, 863);
  RUN_TEST(test_taiTableDynamic, 875);
  RUN_TEST(test_taiTableDynamicDeadZone, 901);
  RUN_TEST(test_ls2009seqInsElectric, 921);
  RUN_TEST(test_ls2009seqInsDumb, 964);
  RUN_TEST(test_ls2009seqDelElectric, 1012);
  RUN_TEST(test_ls2009seqDelDumb, 1055);
  RUN_TEST(test_ls2012seqInsElectric, 1097);
  RUN_TEST(test_ls2012seqInsDumb, 1140);
  RUN_TEST(test_lsEmptyTableDumb, 1189);
  RUN_TEST(test_lsEmptyTableElectric, 1214);

  return (UnityEnd());
}
