/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
void resetTest(void);
extern void test_ValidateGood();
extern void test_ValidateNoHash();
extern void test_ValidateBad();
extern void test_ValidateMalformed();
extern void test_ValidateMalformedShort();
extern void test_ValidateNoLeadZero();
extern void test_tableSelect();
extern void test_loadFileExpire();
extern void test_loadFileTTL();
extern void test_lsQueryPristineState();
extern void test_ls2009faraway();
extern void test_ls2009weekaway();
extern void test_ls2009houraway();
extern void test_ls2009secaway();
extern void test_ls2009onspot();
extern void test_ls2009nodata();
extern void test_ls2009limdata();
extern void test_qryJumpFarAhead();
extern void test_qryJumpAheadToTransition();
extern void test_qryJumpAheadOverTransition();
extern void test_addDynamic();
extern void test_taiEmptyTable();
extern void test_taiTableFixed();
extern void test_taiTableDynamic();
extern void test_taiTableDynamicDeadZone();
extern void test_ls2009seqInsElectric();
extern void test_ls2009seqInsDumb();
extern void test_ls2009seqDelElectric();
extern void test_ls2009seqDelDumb();
extern void test_ls2012seqInsElectric();
extern void test_ls2012seqInsDumb();
extern void test_lsEmptyTableDumb();
extern void test_lsEmptyTableElectric();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}

char *progname;


//=======MAIN=====
int main(int argc, char *argv[])
{
  progname = argv[0];
  Unity.TestFile = "leapsec.c";
  UnityBegin("leapsec.c");
  RUN_TEST(test_ValidateGood, 334);
  RUN_TEST(test_ValidateNoHash, 341);
  RUN_TEST(test_ValidateBad, 348);
  RUN_TEST(test_ValidateMalformed, 355);
  RUN_TEST(test_ValidateMalformedShort, 362);
  RUN_TEST(test_ValidateNoLeadZero, 369);
  RUN_TEST(test_tableSelect, 381);
  RUN_TEST(test_loadFileExpire, 416);
  RUN_TEST(test_loadFileTTL, 432);
  RUN_TEST(test_lsQueryPristineState, 464);
  RUN_TEST(test_ls2009faraway, 476);
  RUN_TEST(test_ls2009weekaway, 493);
  RUN_TEST(test_ls2009houraway, 510);
  RUN_TEST(test_ls2009secaway, 527);
  RUN_TEST(test_ls2009onspot, 544);
  RUN_TEST(test_ls2009nodata, 561);
  RUN_TEST(test_ls2009limdata, 578);
  RUN_TEST(test_qryJumpFarAhead, 599);
  RUN_TEST(test_qryJumpAheadToTransition, 621);
  RUN_TEST(test_qryJumpAheadOverTransition, 643);
  RUN_TEST(test_addDynamic, 669);
  RUN_TEST(test_taiEmptyTable, 847);
  RUN_TEST(test_taiTableFixed, 859);
  RUN_TEST(test_taiTableDynamic, 871);
  RUN_TEST(test_taiTableDynamicDeadZone, 897);
  RUN_TEST(test_ls2009seqInsElectric, 917);
  RUN_TEST(test_ls2009seqInsDumb, 960);
  RUN_TEST(test_ls2009seqDelElectric, 1008);
  RUN_TEST(test_ls2009seqDelDumb, 1051);
  RUN_TEST(test_ls2012seqInsElectric, 1093);
  RUN_TEST(test_ls2012seqInsDumb, 1136);
  RUN_TEST(test_lsEmptyTableDumb, 1185);
  RUN_TEST(test_lsEmptyTableElectric, 1210);

  return (UnityEnd());
}
